name: Enable BTF
description: Enable BTF in the Flourite kernel configuration

inputs:
  version:
    required: false
    default: android14-6.1
  kernel_version:
    required: false
    default: "6.1"
  sublevel:
    required: false
    default: "68"

runs:
  using: composite
  steps:
    - name: Enable BTF
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_DEBUG_INFO=y
          CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT=y
          CONFIG_DEBUG_INFO_BTF=y
